export const GET_CARD_DETAILS_REQUESTED = "GET_CARD_DETAILS_REQUESTED";
export const GET_CARD_DETAILS_SUCCESS = "GET_CARD_DETAILS_SUCCESS";
export const GET_CARD_DETAILS_FAILED = "GET_CARD_DETAILS_FAILED";
export const SET_CARD_LIMIT = "SET_CARD_LIMIT";
